models/Dtp.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Dtp extends ActiveRecord {

    const VICTIM_YES = 1;
    const VICTIM_NO = 0;

    public static function tableName() {
        return 'dtp';
    }

    public function rules() {
        return [
            [['eventDate', 'event', 'latitude', 'longitude'], 'required', 'on' => 'import'],
            ['event', 'in', 'range' => [self::VICTIM_YES, self::VICTIM_NO]],
            [['latitude', 'longitude'], 'integer', 'integerOnly' => false],
            ['eventDate', 'match', 'pattern' => '/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/'],
        ];
    }

    public static function routeFilter($route) {
        $minLt = $route[0]['lat'];
        $maxLt = $route[0]['lat'];

        $minLg = $route[0]['lng'];
        $maxLg = $route[0]['lng'];

        foreach($route as $r) {
            if($r['lat'] > $maxLt) {
                $maxLt = $r['lat'];
            }

            if($r['lat'] < $minLt) {
                $minLt = $r['lat'];
            }

            if($r['lng'] > $maxLg) {
                $maxLg = $r['lng'];
            }

            if($r['lng'] < $minLg) {
                $minLg = $r['lng'];
            }
        }

        return self::find()
            ->where(['between', 'latitude', $minLt, $maxLt])
            ->andWhere(['between', 'longitude', $minLg, $maxLg]);
    }

    public static function importData($filePath) {
        $f = fopen($filePath, 'r');

        fgetcsv($f);
        while(!feof($f)) {
            $line = fgetcsv($f);

            $date = new \DateTime($line[0]);
            $data = [
                'eventDate' => $date->format('Y-m-d H:i:s'),
                'event' => $line[1] == 'ДТП З ПОТЕРПIЛИМИ' ? self::VICTIM_YES : self::VICTIM_NO,
                'latitude' => $line[3],
                'longitude' => $line[2],
            ];

            if($dtp = Dtp::findOne($data)) {
                continue;
            }

            $dtp = new Dtp();
            $dtp->setScenario('import');
            $dtp->setAttributes($data);
            $dtp->save();
        }

        fclose($f);
        unlink($filePath);
    }

    public function attributeLabels() {
        return [
            'event' => 'Подія',
            'eventDate' => 'дата повід.102',
            'latitude' => 'Широта',
            'longitude' => 'Довгота',
        ];
    }
}

models/Task.php
<?php

namespace app\models;
use yii\db\ActiveRecord;

class Task extends ActiveRecord {

    const STATUS_QUEUE = 'queue';
    const STATUS_PROGRESS = 'progress';
    const STATUS_DONE = 'done';
    const STATUS_FAILED = 'failed';

    public static function newFile($path) {
        $t = new self();

        $newPath = __DIR__ . '/../runtime/cache/' . sha1(time() . mt_rand(0, 100));
        move_uploaded_file($path, $newPath);

        $t->setAttributes([
            'fileName' => $newPath,
            'status' => self::STATUS_QUEUE,
        ]);
        $t->save();
    }

    public function rules() {
        return [
            ['fileName', 'safe'],
            ['status', 'in', 'range' => [self::STATUS_QUEUE, self::STATUS_DONE, self::STATUS_FAILED, self::STATUS_PROGRESS]],
        ];
    }

    public static function tableName() {
        return 'task';
    }
}

models/User.php
<?php

namespace app\models;

use yii\db\ActiveRecord;
use yii\web\ForbiddenHttpException;
use Yii;

class User extends ActiveRecord implements \yii\web\IdentityInterface
{
    public static function tableName() {
        return 'user';
    }

    public function rules() {
        return [
            [['email', 'password'], 'required', 'on' => 'login'],
            ['email', 'email'],
            ['email', 'validateEmail', 'on' => 'login'],
        ];
    }

    public function validateEmail($attr) {
        if($user = self::findOne(['email' => $this->$attr])) {
            if(Yii::$app->security->validatePassword($this->password, $user->password)) {
                Yii::$app->user->login($user);
                return true;
            }
        }

        $this->addError($attr, 'Wrong email');
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return self::findOne($id);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new ForbiddenHttpException();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return null;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return false;
    }

    /**
     * Validates password
     *
     * @param  string  $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return false;
    }

    public function attributeLabels() {
        return [
            'email' => 'Електронна пошта',
            'password' => 'Пароль'
        ];

    }
}

controllers/AdminController.php
<?php

namespace app\controllers;

use app\models\Dtp;
use app\models\Task;
use app\models\User;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use Yii;
use yii\web\UploadedFile;

class AdminController extends Controller {

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'import', 'delete'],
                'rules' => [
                    [
                        'actions' => ['index', 'import', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex() {



        return $this->render('index', [
            'taskCount' => Task::find()->where(['status' => Task::STATUS_QUEUE])->count(),
            'dataProvider' => new ActiveDataProvider([
                'query' => Dtp::find(),
            ]),
        ]);

    }

    //Action for demo purposes
    public function actionDelete() {
        Dtp::deleteAll();
        return $this->redirect(['admin/index']);
    }

    public function actionLogout() {
        Yii::$app->user->logout();
        $this->redirect(['site/index']);
    }

    public function actionLogin() {
        if(!Yii::$app->user->isGuest) {
            return $this->redirect(['admin/index']);
        }

        $model = new User();
        $model->setScenario('login');

        if($model->load(Yii::$app->request->post()) && $model->validate()) {
            return $this->redirect(['admin/index']);
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionImport() {

        if($file = UploadedFile::getInstanceByName('import')) {
            Task::newFile($file->tempName);
            return $this->render('import', [
                'queue' => true,
            ]);
        }

        return $this->render('import');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\assets\AngularAsset;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;


class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    public function actionIndex()
    {
        AngularAsset::register($this->view);
        return $this->render('index');
    }

}

views/admin/import.php
<?php
    $this->title= 'Iмпорт';
    use yii\helpers\Url;
?>

<div class="panel panel-default col-lg-offset-3 col-lg-6">
    <div class="panel-heading">
        <h2>Iмпорт</h2>
    </div>
    <div class="panel-body">
        <form method="POST" enctype="multipart/form-data">

            <?php if(isset($queue)): ?>
                <div class="alert alert-info">
                    Файл успiшно доданий до черги iмпорту. Протягом 2-3 хвилин, файл буде повнiстью iмпортований. Новi даннi ви можете переглянути на
                    <b><a href="<?php echo Url::toRoute(['admin/index']) ?>">головнiй сторiнцi</a></b>.
                </div>
            <?php endif; ?>

            <input type="hidden" name="_csrf" value="<?php echo Yii::$app->request->csrfToken ?>" />

            <div class="form-group">
                <label>Оберiть csv файл для iмпорту</label>
                <input type="file" name="import" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary form-control" value="Iмпорт" />
            </div>
        </form>
    </div>
</div>

views/admin/index.php
<?php
    use yii\helpers\Url;
    use yii\grid\GridView;
    use app\models\Dtp;

    $this->title = 'Список ДТП';
?>

<h2>Список ДТП</h2>
<p>
    <a class="btn btn-primary" href="<?php echo Url::toRoute(['admin/import']) ?>">Iмпорт</a>
    <a onclick="confirm('Ви впевненi ?')" class="btn btn-danger" href="<?php echo Url::toRoute(['admin/delete']) ?>">Видалити все</a>
</p>

<?php if($taskCount > 0): ?>

    <div class="alert alert-info">
        <p>На разi в черзi знаходится файлiв: <b><?php echo $taskCount ?></b></p>
        <p>На протязi 1-2 хвилин почнеться обробка...</p>
    </div>

<?php endif;?>

<?php echo GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'id',
        [
            'attribute' => 'event',
            'value' => function($model){
                return $model->event == Dtp::VICTIM_YES ? 'ДТП З ПОТЕРПIЛИМИ' : 'ДТП БЕЗ ПОТЕРПIЛИХ';
            },
        ],
        [
            'attribute' => 'eventDate',
            'value' => function($model) {
                $dt = new DateTime($model->eventDate);
                return $dt->format('d.m.Y H:i:s');
            }
        ],
        'latitude',
        'longitude'
    ],
]); ?>

views/admin/login.php
<?php
    $this->title = 'Вхiд';
?>

<div class="col-lg-offset-4 col-lg-4 panel panel-default">

    <div class="panel-heading">
        <h2>Вхiд</h2>
    </div>
    <div class="panel-body">
<?php

    $form = \yii\widgets\ActiveForm::begin();
    echo $form->field($model, 'email')->hint('Демо вхiд: admin@admin.com');
    echo $form->field($model, 'password')->passwordInput()->hint('Демо вхiд: 123456');

?>
        <div class="form-group">
            <input type="submit" class="btn btn-primary form-control" value="Вхiд" />
        </div>
    </div>

</div>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" ng-app="app">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>

    <script src="https://maps.googleapis.com/maps/api/js?key=<?php echo Yii::$app->params['googleMapsKey'] ?>&libraries=places"></script>
</head>
<body>
<div growl></div>

<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'ДТП',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);

    $items = [
        ['label' => 'Головна', 'url' => ['site/index']],
    ];

    if(!Yii::$app->user->isGuest) {
        $items = array_merge($items, [
            ['label' => 'Список ДТП', 'url' => ['admin/index']],
            ['label' => 'Iмпорт', 'url' => ['admin/import']],
            ['label' => 'Вихiд', 'url' => ['admin/logout'], 'linkOptions' => ['data-method' => 'post']],
        ]);
    } else {
        $items = array_merge($items, [
            ['label' => 'Вхiд для адмiнicтратора', 'url' => ['admin/login'],],
        ]);
    }

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $items,
    ]);

    NavBar::end();
    ?>

    <div class="container" ng-view>
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'ДТП';
?>
<div class="site-index">


</div>